### ISSUE TITLE
Router implementation

### ISSUE THREAD

**Issue by allain** [bloodyowl/rescript-express#3]
Hello I saw you mention that Router binding is not implemented. 

Is that because it's not well suited to ReScript's model?

Is there plans to support it somehow?

**Comment by bloodyowl** [comment]
I didn't implement it yet as I never used it. There'd be no issue implementing it. Is that something you need?

**Comment by allain** [comment]
Not that I need it, but people who know express might expect it to be implemented. I'm really new to ReScript and wouldn't mind giving it a shot though as a learning exercise.

**Comment by sudo97** [comment]
@allain how's it going? I would like to practice with it as well

**Comment by bloodyowl** [comment]
Done by @sudo97 (thanks!) and released in 0.4.0

**Comment by sudo97** [comment]
@bloodyowl if there's something you wish to be implemented and didn't have time, among your Rescript projects, I am still open for practice
