### ISSUE TITLE
TypeError: Express$1 is not a function

### ISSUE THREAD

**Issue by geohuz** [bloodyowl/rescript-express#7]
I installed rescript by following the official document: https://rescript-lang.org/docs/manual/latest/installation
and then follow the installation instructment in this repo, after ``npm start`` the compiler output my bs.js file, then ``node src/my.bs.js`` throw error:  

```
var app = Express$1();
          ^

TypeError: Express$1 is not a function
``

**Comment by bloodyowl** [comment]
Did you check the export you use is the one matching your module system?

https://github.com/bloodyowl/rescript-express#module-system

**Comment by geohuz** [comment]
In my bs-config I have: 

```json
  "package-specs": {
    "module": "commonjs",
    "in-source": true
  },
```

And I don't know where I can setup to pick the export option

**Comment by geohuz** [comment]
Ok I understand I just change to:

```jsx
let app = expressCjs()
```

Then problem fixed!
